### ISSUE TITLE
[BUG] Error when running in extended output mode using Intel MPI

### ISSUE THREAD

**Issue by JanLJL** [RRZE-HPC/MachineState#24]
**Describe the bug**
When running in an environment with Intel MPI, the execution of `impi_info`, which happens when using the extended output, fails.
Even though it is documented that `impi_info` returns a list as shown in their [Developer Reference](https://www.intel.com/content/www/us/en/docs/mpi-library/developer-reference-linux/2021-8/impi-info.html), the output I get is in the format:

```
|<KEY>
 MPI Datatype:
    <VALUE_TYPE>
| <VALUE> | <VALUE_TYPE> |
```

, e.g.:

````
| NAME                                           | DEFAULT VALUE | DATA TYPE |
 ==============================================================================
 |I_MPI_JOB_STARTUP_TIMEOUT
  MPI Datatype:
    MPI_CHAR
 | -1            | MPI_CHAR  |
 |I_MPI_HYDRA_HOST_FILE                                                                                                                                                                                             MPI Datatype:
    MPI_CHAR
 | not defined   | MPI_CHAR  |
````

I tried this with Intel MPI in version 2021.4.0, 2021.7.0, and 2021.9.0.
Obviously, this results in the error that machinestate can't find the value due to it being in a new line.

**To Reproduce**
Have Intel MPI loaded and run the following command:
```bash
$ machinestate -e -a -o test.json
Traceback (most recent call last):
  File "/home/woody/ihpc/ihpc030h/conda/envs/venv310/bin/machinestate", line 33, in <module>
    sys.exit(load_entry_point('MachineState', 'console_scripts', 'machinestate')())
  File "/home/hpc/ihpc/ihpc030h/git/MachineState/machinestate.py", line 3657, in main
    mstate.update()
  File "/home/hpc/ihpc/ihpc030h/git/MachineState/machinestate.py", line 824, in update
    inst.update()
  File "/home/hpc/ihpc/ihpc030h/git/MachineState/machinestate.py", line 821, in update
    data = op.parse(data)
  File "/home/hpc/ihpc/ihpc030h/git/MachineState/machinestate.py", line 578, in parse
    out = self.parser(data)
  File "/home/hpc/ihpc/ihpc030h/git/MachineState/machinestate.py", line 2493, in intelmpiparams
    outdict[llist[1]] = llist[2]
IndexError: list index out of range
```

**Fix**
My workaround is to grep all lines including "|" and processing both the key and the value line in one loop iteration (see diff below).
This only works as long as `impi_info` prints the table with the weird `MPI Datatype:    <VALUE_TYPE>` artifact in between key and value, so I am not sure if we should adjust the machinestate code.

```diff
$ git diff machinestate.py
diff --git a/machinestate.py b/machinestate.py
index 4d65719..85b2ca2 100755
--- a/machinestate.py
+++ b/machinestate.py
@@ -2473,7 +2473,7 @@ class MpiInfo(ListInfoGroup):
                 self.addc("OpenMpiParams", ompi, ompi_args, parse=MpiInfo.openmpiparams)
             impi = which("impi_info")
             if impi and len(impi) > 0 and extended:
-                self.addc("IntelMpiParams", impi, "| grep I_MPI", parse=MpiInfo.intelmpiparams)
+                self.addc("IntelMpiParams", impi, "| grep \"|\"", parse=MpiInfo.intelmpiparams)
     @staticmethod
     def openmpiparams(value):
         outdict = {}
@@ -2486,10 +2486,11 @@ class MpiInfo(ListInfoGroup):
     @staticmethod
     def intelmpiparams(value):
         outdict = {}
-        for line in value.split("\n"):
+        vlist = value.split("\n")
+        for i, line in enumerate(vlist):
             if "I_MPI" not in line: continue
             if not line.strip(): continue
-            llist = [x.strip() for x in line.split("|")]
+            llist = [x.strip() for x in (line + vlist[i+1]).split("|")]
             outdict[llist[1]] = llist[2]
         return outdict
```

**Comment by JanLJL** [comment]
We might want to use the new code together with a version check for Intel MPI 2021.x

**Comment by JanLJL** [comment]
replacing the command in line 2476

https://github.com/RRZE-HPC/MachineState/blob/d21870180592583dfba8b86af00421d46c759fe8/machinestate.py#L2476

with 
```python
self.addc("IntelMpiParams", impi, "| grep \"|\" | perl -p -e 's/\n/ /g' | perl -p -e 's/\|I/\n\|I/g'", parse=MpiInfo.intelmpiparams)
```

should work in all cases
